site_name: My Docs
site_url: https://docs.sink.cool
theme:
  name: material
  palette:
    primary: black
extra:
  alternate:
    - name: English
      link: /
      lang: en
    - name: 中文
      link: /zh/
      lang: zh
